[project]
name = "citibike_feature_pipeline"
version = "0.1.0"
description = "Feature engineering pipeline for CitiBike"
requires-python = ">=3.8,<3.12"

dependencies = [
  "hopsworks==3.7.1",        # ✅ Available on PyPI
  "hsfs==3.7.1",             # ✅ Available and compatible
  "confluent-kafka",
  "packaging",
  "pandas",
  "pyarrow",
  "python-dotenv",
  "requests",
  "holidays",
  "numpy",
  "scikit-learn==1.5.2"
]
