name: citibike_hourly_features_pipeline

on:
  schedule:
    - cron: "2 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  run-feature-engineering:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies using pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run CitiBike feature pipeline and push to Hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        run: python -m src.feature_pipeline
